import Head from "next/head";
import "bulma/css/bulma.css";
import styles from "../styles/Home.module.css";

export default function Home() {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Voting App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
            
        <a href="#"></a>
        </div>
      </main>
    </div>
  );
}
